# -*- coding: utf-8 -*-
"""Reflectancia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVHAOFBHAkxwkyZXCWxyhTQyvClecyfS
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the CSV file into a pandas DataFrame with the correct delimiter, decimal, and header
# skiprows=[0] skips the very first line of the file.
# header=0 then tells pandas that the first *remaining* line is the header.
df = pd.read_csv('/content/algodon.csv', sep=';', decimal=',', header=0, skiprows=[0])

# Clean column names: strip whitespace and drop 'Unnamed' columns
df.columns = df.columns.str.strip()
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

# Display the first 5 rows of the DataFrame to understand its structure
print("First 5 rows of the DataFrame:")
display(df.head())

# Print the exact column names to verify
print("DataFrame columns after cleaning:")
print(df.columns.tolist())



# Assuming the column names are 'Wavenumbers [1/cm]' (wavelength) and 'Reflectance' (reflectance) after cleaning

# Create the plot
plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df)
plt.title('Reflectance vs. Wavelength')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.show()

# Load lino.csv
df_lino = pd.read_csv('/content/lino.csv', sep=';', decimal=',', header=0, skiprows=[0])
df_lino.columns = df_lino.columns.str.strip()
df_lino = df_lino.loc[:, ~df_lino.columns.str.contains('^Unnamed')]
print("First 5 rows of Lino DataFrame:")
display(df_lino.head())

# Load poliester.csv
df_poliester = pd.read_csv('/content/poliester.csv', sep=';', decimal=',', header=0, skiprows=[0])
df_poliester.columns = df_poliester.columns.str.strip()
df_poliester = df_poliester.loc[:, ~df_poliester.columns.str.contains('^Unnamed')]
print("First 5 rows of Poliester DataFrame:")
display(df_poliester.head())

# Load tencel.csv
df_tencel = pd.read_csv('/content/tencel.csv', sep=';', decimal=',', header=0, skiprows=[0])
df_tencel.columns = df_tencel.columns.str.strip()
df_tencel = df_tencel.loc[:, ~df_tencel.columns.str.contains('^Unnamed')]
print("First 5 rows of Tencel DataFrame:")
display(df_tencel.head())

# rango total
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np # Import numpy for linspace and other operations

# Define common wavelength range for all plots
min_wavelength_for_plot_nm = 190
max_wavelength_for_plot_nm = 2000

# Create the plot with all datasets and a legend
plt.figure(figsize=(12, 7))

# Plot textile data
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df, label='Algodón')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_lino, label='Lino')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_poliester, label='Poliéster')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_tencel, label='Tencel')

# --- Process Espectro_solar_alta_resol.csv ---
df_solar = pd.read_csv('/content/Espectro_solar_alta_resol.csv', sep=',', decimal='.', header=0)
df_solar.columns = df_solar.columns.str.strip()
wavelength_col_solar = 'Longitud_de_Onda_nm'
intensity_col_solar = 'Irradiancia_W_m2_nm'

df_solar_filtered = df_solar[
    (df_solar[wavelength_col_solar] >= min_wavelength_for_plot_nm) &
    (df_solar[wavelength_col_solar] <= max_wavelength_for_plot_nm)
].sort_values(by=wavelength_col_solar)

max_solar_intensity = df_solar_filtered[intensity_col_solar].max()
if max_solar_intensity > 0:
    df_solar_filtered['Normalized_Solar_Intensity'] = df_solar_filtered[intensity_col_solar] / max_solar_intensity * 100
else:
    df_solar_filtered['Normalized_Solar_Intensity'] = 0

# Plot Solar Spectrum as a shaded area
plt.fill_between(df_solar_filtered[wavelength_col_solar], 0, df_solar_filtered['Normalized_Solar_Intensity'], label='Espectro Solar (Normalizado)', color='salmon', alpha=0.3)


plt.title('Reflectancia para Diferentes Telas', fontsize=16)
plt.xlabel('Longitud de onda (nm)', fontsize=16)
plt.ylabel('Reflectancia (%)', fontsize=16)
plt.grid(True)
plt.legend(title='Material', fontsize=10, loc='lower right')
plt.ylim(0, 100) # Set y-axis limit from 0 to 100
plt.yticks(range(0, 101, 10), fontsize=10) # Set y-axis ticks from 0 to 100 with step 10
plt.xlim(min_wavelength_for_plot_nm, max_wavelength_for_plot_nm) # Set x-axis limit using defined range
plt.xticks(fontsize=10)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np # Import numpy for linspace and other operations

# Define common wavelength range for this plot
min_wavelength_for_visible_plot_nm = 325
max_wavelength_for_visible_plot_nm = 1200

# Create the plot with all datasets and a legend
plt.figure(figsize=(12, 7))

# Plot textile data
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df, label='Algodón')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_lino, label='Lino')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_poliester, label='Poliéster')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_tencel, label='Tencel')

# --- Process Espectro_solar_alta_resol.csv ---
df_solar = pd.read_csv('/content/Espectro_solar_alta_resol.csv', sep=',', decimal='.', header=0)
df_solar.columns = df_solar.columns.str.strip()
wavelength_col_solar = 'Longitud_de_Onda_nm'
intensity_col_solar = 'Irradiancia_W_m2_nm'

df_solar_filtered = df_solar[
    (df_solar[wavelength_col_solar] >= min_wavelength_for_visible_plot_nm) &
    (df_solar[wavelength_col_solar] <= max_wavelength_for_visible_plot_nm)
].sort_values(by=wavelength_col_solar)

max_solar_intensity = df_solar_filtered[intensity_col_solar].max()
if max_solar_intensity > 0:
    df_solar_filtered['Normalized_Solar_Intensity'] = df_solar_filtered[intensity_col_solar] / max_solar_intensity * 100
else:
    df_solar_filtered['Normalized_Solar_Intensity'] = 0

# Plot Solar Spectrum as a shaded area
plt.fill_between(df_solar_filtered[wavelength_col_solar], 0, df_solar_filtered['Normalized_Solar_Intensity'], label='Espectro Solar (Normalizado)', color='salmon', alpha=0.3)

plt.title('Reflectancia en el visible para Diferentes Telas', fontsize=16)
plt.xlabel('Longitud de onda (nm)', fontsize=16)
plt.ylabel('Reflectancia (%)', fontsize=16)
plt.grid(True)
plt.legend(title='Material', loc='lower right')
plt.ylim(0, 100) # Set y-axis limit from 0 to 100
plt.yticks(range(0, 101, 10)) # Set y-axis ticks from 0 to 100 with step 10
plt.xlim(min_wavelength_for_visible_plot_nm, max_wavelength_for_visible_plot_nm) # Set x-axis limit using defined range
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df, label='Algodón', color='blue')
plt.title('Reflectancia frente a Longitud de Onda - Algodón (325-1200 nm)')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(325, 1200)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_lino, label='Lino', color='orange')
plt.title('Reflectancia frente a Longitud de Onda - Lino (325-1200 nm)')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(325, 1200)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_poliester, label='Poliéster', color='green')
plt.title('Reflectancia frente a Longitud de Onda - Poliéster (325-1200 nm)')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(325, 1200)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_tencel, label='Tencel', color='red')
plt.title('Reflectancia frente a Longitud de Onda - Tencel (325-1200 nm)')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(325, 1200)
plt.legend()
plt.show()

"""## Graphs for NC, MCE, and CA materials"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load NC.csv
df_nc = pd.read_csv('/content/NC.csv', sep=';', decimal=',', header=0, skiprows=[0])
df_nc.columns = df_nc.columns.str.strip()
df_nc = df_nc.loc[:, ~df_nc.columns.str.contains('^Unnamed')]
print("First 5 rows of NC DataFrame:")
display(df_nc.head())

# Load MCE.csv
df_mce = pd.read_csv('/content/MCE.csv', sep=';', decimal=',', header=0, skiprows=[0])
df_mce.columns = df_mce.columns.str.strip()
df_mce = df_mce.loc[:, ~df_mce.columns.str.contains('^Unnamed')]
print("First 5 rows of MCE DataFrame:")
display(df_mce.head())

# Load CA.csv
df_ca = pd.read_csv('/content/CA.csv', sep=';', decimal=',', header=0, skiprows=[0])
df_ca.columns = df_ca.columns.str.strip()
df_ca = df_ca.loc[:, ~df_ca.columns.str.contains('^Unnamed')]
print("First 5 rows of CA DataFrame:")
display(df_ca.head())

"""### Combined plot for NC, MCE, and CA"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Create the plot with all new datasets and a legend
plt.figure(figsize=(12, 7))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_nc, label='NC', color='steelblue')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_ca, label='CA', color='magenta')
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_mce, label='MCE', color='olivedrab')

plt.title('Reflectancia frente a Longitud de Onda para NC, MCE y CA')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.legend(title='Material')
plt.ylim(0, 100) # Set y-axis limit from 0 to 100
plt.yticks(range(0, 101, 10)) # Set y-axis ticks from 0 to 100 with step 10
plt.xlim(190, 2000) # Set x-axis limit from 325 to 1200
plt.show()

"""### Individual plots for NC, MCE, and CA"""

plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_nc, label='NC', color='steelblue')
plt.title('Reflectancia frente a Longitud de Onda - NC')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(325, 1200)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_mce, label='MCE', color='olivedrab')
plt.title('Reflectancia frente a Longitud de Onda - MCE')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(325, 1200)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(x='Wavenumbers [1/cm]', y='Reflectance', data=df_ca, label='CA', color='magenta')
plt.title('Reflectancia frente a Longitud de Onda - CA')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(325, 1200)
plt.legend()
plt.show()

"""gráfica total"""

import numpy as np
import matplotlib.pyplot as plt

def planck_blackbody_radiation(wavelength_nm, temperature_k):
    """
    Calculates the spectral radiance of a blackbody according to Planck's Law
    and normalizes it to the maximum value.

    Args:
        wavelength_nm (float or np.ndarray): Wavelength in nanometers (nm).
        temperature_k (float): Temperature in Kelvin (K).

    Returns:
        float or np.ndarray: Normalized spectral radiance B(lambda, T) (scaled 0 to 1).
    """
    # Physical constants
    h = 6.62607015e-34  # Planck's constant (J*s)
    c = 2.99792458e8    # Speed of light (m/s)
    k = 1.380649e-23    # Boltzmann constant (J/K)

    # Convert wavelength from nanometers to meters
    wavelength_m = wavelength_nm * 1e-9

    # Avoid division by zero and very small numbers for exponential
    if temperature_k <= 0:
        return np.zeros_like(wavelength_m)

    # Calculate the terms in Planck's Law
    term1 = 2 * h * c**2
    term2 = wavelength_m**5
    term3_exponent = (h * c) / (wavelength_m * k * temperature_k)

    # Handle potential overflow/underflow in exponential
    exp_minus_1 = np.exp(term3_exponent) - 1

    radiance = np.zeros_like(wavelength_m, dtype=float)
    valid_indices = (wavelength_m > 0) & (exp_minus_1 > 1e-300)

    radiance[valid_indices] = (term1 / term2[valid_indices]) * (1 / exp_minus_1[valid_indices])

    # --- Normalization step ---
    max_radiance = np.max(radiance)
    if max_radiance > 0:
        normalized_radiance = radiance / max_radiance
    else:
        normalized_radiance = np.zeros_like(radiance)

    return normalized_radiance


# --- Demostración de uso ---
# Definir un rango de longitudes de onda en nanómetros
wavelengths_nm = np.linspace(100, 1000, 300) # De 100 nm (UV) a 3000 nm (IR)

# Definir algunas temperaturas en Kelvin
temperatures_k = [5000] # 300K ~ 27C (temperatura ambiente), 5000K (similar al sol)

plt.figure(figsize=(12, 8))

for T in temperatures_k:
    radiance = planck_blackbody_radiation(wavelengths_nm, T)
    plt.plot(wavelengths_nm, radiance, label=f'T = {T} K')

plt.title('Distribución de Cuerpo Negro de Planck Normalizada')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Radiancia Espectral Normalizada') # Update label for normalized output
plt.legend()
plt.grid(True)
plt.ylim(0, 1.1) # Set y-axis limit for normalized data
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd # Ensure pandas is imported

plt.figure(figsize=(10, 8))

# --- Process df_ca (Material CA) ---
# The user clarified that 'Wavenumbers [1/cm]' in df_ca is actually Wavelengths [nm]
df_ca_plot_data = df_ca.copy()
df_ca_plot_data['Wavelengths [nm]'] = df_ca_plot_data['Wavenumbers [1/cm]']

# Define a broad wavelength range for plotting that encompasses all data
# Solar spectrum is roughly 280-2500 nm
# Planck 5900K peak is around 500 nm
# To show all relevant parts, we'll choose a range that includes solar, Planck peak, and some CA.
min_wavelength_for_plot_nm = 300  # Start from UV-Visible
max_wavelength_for_plot_nm = 1600 # Extend to near-IR,

# Filter df_ca data to fit the chosen wavelength range
df_ca_filtered_for_plot = df_ca_plot_data[
    (df_ca_plot_data['Wavelengths [nm]'] >= min_wavelength_for_plot_nm) &
    (df_ca_plot_data['Wavelengths [nm]'] <= max_wavelength_for_plot_nm)
].sort_values(by='Wavelengths [nm]')

sns.lineplot(x='Wavelengths [nm]', y='Reflectance', data=df_ca_filtered_for_plot, label='CA', color='magenta')

# --- Process df_nc (Material NC) ---
df_nc_plot_data = df_nc.copy()
df_nc_plot_data['Wavelengths [nm]'] = df_nc_plot_data['Wavenumbers [1/cm]']
df_nc_filtered_for_plot = df_nc_plot_data[
    (df_nc_plot_data['Wavelengths [nm]'] >= min_wavelength_for_plot_nm) &
    (df_nc_plot_data['Wavelengths [nm]'] <= max_wavelength_for_plot_nm)
].sort_values(by='Wavelengths [nm]')
sns.lineplot(x='Wavelengths [nm]', y='Reflectance', data=df_nc_filtered_for_plot, label='NC', color='steelblue')

# --- Process df_mce (Material MCE) ---
df_mce_plot_data = df_mce.copy()
df_mce_plot_data['Wavelengths [nm]'] = df_mce_plot_data['Wavenumbers [1/cm]']
df_mce_filtered_for_plot = df_mce_plot_data[
    (df_mce_plot_data['Wavelengths [nm]'] >= min_wavelength_for_plot_nm) &
    (df_mce_plot_data['Wavelengths [nm]'] <= max_wavelength_for_plot_nm)
].sort_values(by='Wavelengths [nm]')
sns.lineplot(x='Wavelengths [nm]', y='Reflectance', data=df_mce_filtered_for_plot, label='MCE', color='olivedrab')

# --- Process Espectro_solar.csv ---
#
# Correctly load Espectro_solar_alta_resol.csv: comma as separator, header=0
# Assuming the new file has a proper header on the first line after user's update.
df_solar = pd.read_csv('/content/Espectro_solar_alta_resol.csv', sep=',', decimal='.', header=0)

# Clean column names (e.g., remove extra spaces)
df_solar.columns = df_solar.columns.str.strip()

# Ensure column names match what's in the CSV
# Based on common solar spectrum data, we expect 'Longitud_de_Onda_nm' and 'Irradiancia_W_m2_nm'
wavelength_col_solar = 'Longitud_de_Onda_nm'
intensity_col_solar = 'Irradiancia_W_m2_nm'

# Filter solar data to fit the chosen wavelength range
df_solar_filtered = df_solar[
    (df_solar[wavelength_col_solar] >= min_wavelength_for_plot_nm) &
    (df_solar[wavelength_col_solar] <= max_wavelength_for_plot_nm)
].sort_values(by=wavelength_col_solar)

# Normalize Solar Spectrum Intensity
max_solar_intensity = df_solar_filtered[intensity_col_solar].max()
if max_solar_intensity > 0:
    df_solar_filtered['Normalized_Solar_Intensity'] = df_solar_filtered[intensity_col_solar] / max_solar_intensity * 100
else:
    df_solar_filtered['Normalized_Solar_Intensity'] = 0

# Plot Solar Spectrum as a shaded area
plt.fill_between(df_solar_filtered[wavelength_col_solar], 0, df_solar_filtered['Normalized_Solar_Intensity'], label='Espectro Solar (Normalizado)', color='salmon', alpha=0.3) # Increased alpha to 0.9

# --- Process Planck Distribution ---
# Generate wavelengths for Planck function directly in the plot range
wavelengths_for_planck_plot_nm = np.linspace(min_wavelength_for_plot_nm, max_wavelength_for_plot_nm, 500)

# Calculate Planck radiation for the given temperature (5900 K)
planck_temp = 5900
normalized_planck_radiance = planck_blackbody_radiation(wavelengths_for_planck_plot_nm, planck_temp)

# Scale the normalized Planck radiance (0-1) to 0-100 to compare with Reflectance (%)
sns.lineplot(x=wavelengths_for_planck_plot_nm, y=normalized_planck_radiance * 100, label=f'Planck {planck_temp} K (Normalizada)', color='black', linestyle='--')

# --- Plotting configurations ---
plt.title('Reflectancia, Planck y Espectro Solar Normalizados para CA, NC y MCE frente a Longitud de Onda')
plt.xlabel('Longitud de onda (nm)')
plt.ylabel('Reflectancia (%) / Radiancia Normalizada (%)')
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(min_wavelength_for_plot_nm, max_wavelength_for_plot_nm)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd # Ensure pandas is imported

plt.figure(figsize=(10, 8))

# --- Process df_ca (Material CA) ---
# The user clarified that 'Wavenumbers [1/cm]' in df_ca is actually Wavelengths [nm]
df_ca_plot_data = df_ca.copy()
df_ca_plot_data['Wavelengths [nm]'] = df_ca_plot_data['Wavenumbers [1/cm]']

# Define a broad wavelength range for plotting that encompasses all data
# Solar spectrum is roughly 280-2500 nm
# Planck 5900K peak is around 500 nm
# To show all relevant parts, we'll choose a range that includes solar, Planck peak, and some CA.
min_wavelength_for_plot_nm = 300  # Start from UV-Visible
max_wavelength_for_plot_nm = 1600 # Extend to near-IR,

# Filter df_ca data to fit the chosen wavelength range
df_ca_filtered_for_plot = df_ca_plot_data[
    (df_ca_plot_data['Wavelengths [nm]'] >= min_wavelength_for_plot_nm) &
    (df_ca_plot_data['Wavelengths [nm]'] <= max_wavelength_for_plot_nm)
].sort_values(by='Wavelengths [nm]')

sns.lineplot(x='Wavelengths [nm]', y='Reflectance', data=df_ca_filtered_for_plot, label='CA', color='magenta')

# --- Process df_nc (Material NC) ---
df_nc_plot_data = df_nc.copy()
df_nc_plot_data['Wavelengths [nm]'] = df_nc_plot_data['Wavenumbers [1/cm]']
df_nc_filtered_for_plot = df_nc_plot_data[
    (df_nc_plot_data['Wavelengths [nm]'] >= min_wavelength_for_plot_nm) &
    (df_nc_plot_data['Wavelengths [nm]'] <= max_wavelength_for_plot_nm)
].sort_values(by='Wavelengths [nm]')
sns.lineplot(x='Wavelengths [nm]', y='Reflectance', data=df_nc_filtered_for_plot, label='NC', color='steelblue')

# --- Process df_mce (Material MCE) ---
df_mce_plot_data = df_mce.copy()
df_mce_plot_data['Wavelengths [nm]'] = df_mce_plot_data['Wavenumbers [1/cm]']
df_mce_filtered_for_plot = df_mce_plot_data[
    (df_mce_plot_data['Wavelengths [nm]'] >= min_wavelength_for_plot_nm) &
    (df_mce_plot_data['Wavelengths [nm]'] <= max_wavelength_for_plot_nm)
].sort_values(by='Wavelengths [nm]')
sns.lineplot(x='Wavelengths [nm]', y='Reflectance', data=df_mce_filtered_for_plot, label='MCE', color='olivedrab')

# --- Process Espectro_solar.csv ---
#
# Correctly load Espectro_solar_alta_resol.csv: comma as separator, header=0
# Assuming the new file has a proper header on the first line after user's update.
df_solar = pd.read_csv('/content/Espectro_solar_alta_resol.csv', sep=',', decimal='.', header=0)

# Clean column names (e.g., remove extra spaces)
df_solar.columns = df_solar.columns.str.strip()

# Ensure column names match what's in the CSV
# Based on common solar spectrum data, we expect 'Longitud_de_Onda_nm' and 'Irradiancia_W_m2_nm'
wavelength_col_solar = 'Longitud_de_Onda_nm'
intensity_col_solar = 'Irradiancia_W_m2_nm'

# Filter solar data to fit the chosen wavelength range
df_solar_filtered = df_solar[
    (df_solar[wavelength_col_solar] >= min_wavelength_for_plot_nm) &
    (df_solar[wavelength_col_solar] <= max_wavelength_for_plot_nm)
].sort_values(by=wavelength_col_solar)

# Normalize Solar Spectrum Intensity
max_solar_intensity = df_solar_filtered[intensity_col_solar].max()
if max_solar_intensity > 0:
    df_solar_filtered['Normalized_Solar_Intensity'] = df_solar_filtered[intensity_col_solar] / max_solar_intensity * 100
else:
    df_solar_filtered['Normalized_Solar_Intensity'] = 0

# Plot Solar Spectrum as a shaded area
plt.fill_between(df_solar_filtered[wavelength_col_solar], 0, df_solar_filtered['Normalized_Solar_Intensity'], label='Espectro Solar (Normalizado)', color='salmon', alpha=0.3) # Increased alpha to 0.9

# --- Process Planck Distribution ---
# Generate wavelengths for Planck function directly in the plot range
wavelengths_for_planck_plot_nm = np.linspace(min_wavelength_for_plot_nm, max_wavelength_for_plot_nm, 500)

# Calculate Planck radiation for the given temperature (5900 K)
planck_temp = 5900
normalized_planck_radiance = planck_blackbody_radiation(wavelengths_for_planck_plot_nm, planck_temp)

# Scale the normalized Planck radiance (0-1) to 0-100 to compare with Reflectance (%)
sns.lineplot(x=wavelengths_for_planck_plot_nm, y=normalized_planck_radiance * 100, label=f'Planck {planck_temp} K (Normalizada)', color='black', linestyle='--')

# --- Plotting configurations ---
plt.title('Reflectancia para CA, NC y MCE frente a Longitud de Onda', fontsize=16)
plt.xlabel('Longitud de onda (nm)', fontsize=16)
plt.ylabel('Reflectancia (%)', fontsize=16)
plt.grid(True)
plt.ylim(0, 100)
plt.yticks(range(0, 101, 10))
plt.xlim(min_wavelength_for_plot_nm, 1200)
plt.legend()
plt.show()